name: choose_presenter_bot

on:
  issues:
    types:
      - opened

jobs:
  choose_presenter_bot:
    runs-on: ubuntu-latest
    steps: 
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Get study date
        id: study-date
        run: echo "::set-output name=date::$(date -d '16 hours' +%Y.%m.%d)"
        
      - name: POST List of Presenters to Slack
        shell: bash
        run: | 
          MESSAGE+="${{steps.date.outputs.study-date}} 발표자 뽑기 결과 \n--------------------------------\n"

          all_team_members=("수민" "서연" "형선" "슬" "주연" "수현" "철희" "유리" "지훈")

          exclude_team_members=("수민")

          topics=("주제1" "주제2" "주제3" "주제4")
          
          selected_team_members=()
          while [ ${#selected_team_members[@]} -lt 4 ]; do
              random_member=${all_team_members[$((RANDOM % ${#all_team_members[@]}))]}
              # 제외할 팀원이 아니면서 이미 선택되지 않은 경우에만 추가
              if [[ ! " ${exclude_team_members[@]} " =~ " $random_member " ]] && [[ ! " ${selected_team_members[@]} " =~ " $random_member " ]]; then
                  selected_team_members+=("$random_member")
              fi
          done

          for i in "${!selected_team_members[@]}"; do
              member="${selected_team_members[$i]}"
              topic="${topics[$i]}"
              MESSAGE+="$member - $topic"
              MESSAGE+="\n"
          done
        
          MESSAGE+="${{steps.date.outputs.date}}"
          MESSAGE+="\n"
          MESSAGE+="${{steps.date.outputs.study-date}}"
        
          curl -X POST --data-urlencode "payload={\"channel\": \"#playground\", \"username\": \"뽑기봇\", \"text\": \"${MESSAGE}\", \"icon_emoji\": \":ghost:\"}" {% raw %}${{ secrets.SLACK_WEBHOOK_URL }}{% endraw %}

          
