name: Workflow for testing ping action
on: workflow_dispatch

jobs:
  build:
    name: ping
    runs-on: ubuntu-latest
    steps:
      - name: Ping my site
        uses: Leocardoso94/is-my-site-up@v1.2    
        with:
          site: "https://6556-218-155-31-211.ngrok-free.app"
